### ISSUE TITLE
点击输入框的地方会关闭原有的输入框

### ISSUE THREAD

**Issue by HOMIEFF** [iscottt/somnia-issues#1]
就是点击主题的搜索框，虽然可以直接输入文字的但是如果我习惯性想用鼠标点击一下输入框
![Snipaste_2024-06-17_08-08-08](https://github.com/iscottt/somnia-issues/assets/79042804/26eb8520-d58e-410f-94e5-36bfb227ae21)
![Snipaste_2024-06-17_08-08-31](https://github.com/iscottt/somnia-issues/assets/79042804/e594d3ad-9e72-49d2-b5aa-1af38bb45f89)
![Snipaste_2024-06-17_08-08-51](https://github.com/iscottt/somnia-issues/assets/79042804/ff16bd7b-4b6a-4f58-a982-839d96fbf13e)
那搜索框就会直接关闭，除了主题首页的搜索框会这样还有登录、注册的输入框会这样，就是点击一下光标所在那行整个登录或注册窗口就会直接关闭了

**Comment by iscottt** [comment]
经验证为弹窗bug，下个版本优化
