### ISSUE TITLE
图片灯箱缩放感觉怪怪的

### ISSUE THREAD

**Issue by HOMIEFF** [iscottt/somnia-issues#2]
![Snipaste_2024-06-17_08-48-54](https://github.com/iscottt/somnia-issues/assets/79042804/04a4fe15-7bcf-49e4-87c5-221744f426e5)
上图是我在后台编辑时图片缩小时的状态，能看出宽高并没有挤压或者撕裂的感觉
但是下图是我发表后的灯箱，这个灯箱感觉宽高比例不一致有种拉扯撕裂的感觉
![Snipaste_2024-06-17_08-51-03](https://github.com/iscottt/somnia-issues/assets/79042804/d248ff2d-a827-4a9b-9451-0b1b003ce909)

**Comment by iscottt** [comment]
下个版本优化
