### ISSUE TITLE
建议将手机端的图片排版改成双栏的，目前这样看感觉旁边多了一部分，能不能实现双栏铺满或者双栏自适应呢？

### ISSUE THREAD

**Issue by HOMIEFF** [iscottt/somnia-issues#4]
![Screenshot_2024-06-17-21-10-15-687_com microsoft emmx](https://github.com/iscottt/somnia-issues/assets/79042804/c4f7daf3-dd50-4ff6-8258-d7ba890d61de)

**Comment by iscottt** [comment]
已修改
